name: CI

on: [push, pull_request]

jobs:
  test:
    name: Tests with Ruby ${{ matrix.ruby_version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - '2.7'
          - '3.0'
          - '3.1'

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby_version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run tests
      env:
        RAILS_ENV: test
      run: |
        bundle exec rake
